// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Metadata {
    #[prost(uint32, tag = "1")]
    pub worker_id: u32,
    #[prost(uint64, tag = "2")]
    pub received_epoch: u64,
    #[prost(uint64, tag = "3")]
    pub decoded_epoch: u64,
    #[prost(uint32, tag = "4")]
    pub bytes: u32,
    #[prost(string, tag = "5")]
    pub client_ip: ::prost::alloc::string::String,
    #[prost(uint32, tag = "6")]
    pub client_port: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NormalizedData {
    #[prost(string, tag = "1")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    pub latitude: f64,
    #[prost(double, tag = "3")]
    pub longitude: f64,
    #[prost(double, tag = "4")]
    pub speed: f64,
    #[prost(double, tag = "5")]
    pub course: f64,
    #[prost(bool, tag = "6")]
    pub engine_on: bool,
    #[prost(uint32, tag = "7")]
    pub satellites: u32,
    #[prost(enumeration = "MessageClass", tag = "8")]
    pub msg_class: i32,
    #[prost(uint64, tag = "9")]
    pub gps_epoch: u64,
    #[prost(double, tag = "10")]
    pub main_battery_voltage: f64,
    #[prost(double, tag = "11")]
    pub backup_battery_voltage: f64,
    #[prost(uint64, tag = "12")]
    pub odometer_mts: u64,
    #[prost(uint64, tag = "13")]
    pub trip_distance_mts: u64,
    /// Additional fields that may be present in the normalized data
    #[prost(map = "string, string", tag = "14")]
    pub additional_fields: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SuntechDecoded {
    /// Suntech-specific decoded fields
    #[prost(map = "string, string", tag = "1")]
    pub fields: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueclinkDecoded {
    /// Queclink-specific decoded fields
    #[prost(map = "string, string", tag = "1")]
    pub fields: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KafkaMessage {
    #[prost(string, tag = "1")]
    pub uuid: ::prost::alloc::string::String,
    /// Normalized/homogenized data
    #[prost(map = "string, string", tag = "4")]
    pub data: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Message metadata
    #[prost(message, optional, tag = "5")]
    pub metadata: ::core::option::Option<Metadata>,
    /// Raw payload (original message)
    #[prost(string, tag = "6")]
    pub raw: ::prost::alloc::string::String,
    /// Decoded message as oneof per vendor
    #[prost(oneof = "kafka_message::Decoded", tags = "2, 3")]
    pub decoded: ::core::option::Option<kafka_message::Decoded>,
}
/// Nested message and enum types in `KafkaMessage`.
pub mod kafka_message {
    /// Decoded message as oneof per vendor
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Decoded {
        #[prost(message, tag = "2")]
        Suntech(super::SuntechDecoded),
        #[prost(message, tag = "3")]
        Queclink(super::QueclinkDecoded),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Communication {
    #[prost(string, tag = "1")]
    pub uuid: ::prost::alloc::string::String,
    #[prost(enumeration = "Vendor", tag = "2")]
    pub vendor: i32,
    #[prost(message, optional, tag = "3")]
    pub data: ::core::option::Option<NormalizedData>,
    #[prost(message, optional, tag = "4")]
    pub metadata: ::core::option::Option<Metadata>,
    /// Decoded payload as bytes with content type
    /// This allows flexibility: today it's JSON, tomorrow it could be
    /// vendor-specific protobuf or other binary formats
    #[prost(bytes = "vec", tag = "20")]
    pub decoded_payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "21")]
    pub decoded_content_type: ::prost::alloc::string::String,
    /// Raw payload (original message or hex representation)
    #[prost(string, tag = "22")]
    pub raw: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Vendor {
    Unknown = 0,
    Suntech = 1,
    Queclink = 2,
}
impl Vendor {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Vendor::Unknown => "VENDOR_UNKNOWN",
            Vendor::Suntech => "SUNTECH",
            Vendor::Queclink => "QUECLINK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VENDOR_UNKNOWN" => Some(Self::Unknown),
            "SUNTECH" => Some(Self::Suntech),
            "QUECLINK" => Some(Self::Queclink),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessageClass {
    MsgUnknown = 0,
    Status = 1,
    Event = 2,
    Alert = 3,
}
impl MessageClass {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            MessageClass::MsgUnknown => "MSG_UNKNOWN",
            MessageClass::Status => "STATUS",
            MessageClass::Event => "EVENT",
            MessageClass::Alert => "ALERT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MSG_UNKNOWN" => Some(Self::MsgUnknown),
            "STATUS" => Some(Self::Status),
            "EVENT" => Some(Self::Event),
            "ALERT" => Some(Self::Alert),
            _ => None,
        }
    }
}
